# Generated by Django 4.0.5 on 2022-06-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='zoom_level',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
