# Generated by Django 4.0.5 on 2022-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_module', '0002_project_category_project_zoom_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('thermography', 'thermography'), ('topography', 'topography')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='zoom_level',
            field=models.CharField(blank=True, default='15', max_length=10, null=True),
        ),
    ]
