# Generated by Django 4.0.5 on 2022-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_module', '0003_alter_project_category_alter_project_zoom_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('thermography', 'thermography'), ('topography', 'topography'), ('grading', 'grading'), ('due diligence', 'due diligence')], default='', max_length=100, null=True),
        ),
    ]
