# Generated by Django 4.0.5 on 2022-07-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_module', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprocesseddata',
            name='csv_path',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectprocesseddata',
            name='dtm_legend',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectprocesseddata',
            name='slope_legend',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
