# Generated by Django 4.0.5 on 2022-07-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_module', '0005_projectprocesseddata_csv_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprocesseddata',
            name='grading_layers',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
