# Generated by Django 4.0.5 on 2022-07-11 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_module', '0002_alter_project_id_alter_projectdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('line', 'line'), ('poly', 'poly'), ('point', 'point')], default='', max_length=20)),
                ('label', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 7, 11, 12, 59, 22, 623230))),
                ('measurements', models.CharField(default='', max_length=255)),
                ('polygon', models.TextField(blank=True, default={}, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('label', models.CharField(default='Undefined', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 7, 11, 12, 59, 22, 622229))),
                ('polygon', models.TextField(blank=True, default=[], null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_module.project')),
            ],
        ),
    ]
